name: unit_test

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [ 7.4, 8.0 ]

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v5 # or alternative dependency management
            - name: "phpunit ${{ matrix.php-version }}"
              uses: php-actions/phpunit@v3
              with:
                  php_version: ${{ matrix.php-version }}
                  php_extensions: xdebug
                  bootstrap: vendor/autoload.php
                  configuration: test/phpunit.xml
                  args: --coverage-text
              env:
                  XDEBUG_MODE: coverage
