name: unit_test

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: [ 8.0, 8.1 ]

        steps:
            -   uses: actions/checkout@v2

            -   uses: php-actions/composer@v6

            -   name: PHPUnit Tests
                uses: php-actions/phpunit@v3
                env:
                    TEST_NAME: Mark
                with:
                    bootstrap: vendor/autoload.php
                    configuration: phpunit-ci.xml
                    args: --coverage-text
                    php_version: ${{matrix.php-versions}}

