name: unit_test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: [ 8.0, 8.1 ]

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v6 # or alternative dependency management
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{matrix.php-versions}}
                  tools: phpunit:9.5
            - name: add bootstrap cachedir
              run: mkdir /tmp/bootstrap && mkdir /tmp/bootstrap/cache && chmod 777 /tmp/bootstrap/cache && mkdir /tmp/storage && chmod 777 /tmp/storage
              shell: bash
            - name: PHPUnit Tests
              run: composer test-ci
              shell: bash
