name: unit_test

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [ 7.4, 8.0 ]

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v4 # or alternative dependency management
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{matrix.php-versions}}
            - name: Install dependencies
              uses: php-actions/composer@v4
              with:
                  dev: yes
                  args: --prefer-source
            - name: PHPUnit Tests
              run: vendor/bin/phpunit -v -c phpunit.xml
